// Dữ liệu ngân hàng Việt Nam
// Nguồn: https://github.com/vietnam-maps/vietnam-banks
export const banks = [
    { "id": 1, "name": "Ngân hàng thương mại cổ phần An Bình", "shortName": "ABBank", "logo": "https://api.vietqr.io/img/ABBank.png" },
    { "id": 2, "name": "Ngân hàng thương mại cổ phần Á Châu", "shortName": "ACB", "logo": "https://api.vietqr.io/img/ACB.png" },
    { "id": 4, "name": "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam", "shortName": "Agribank", "logo": "https://api.vietqr.io/img/Agribank.png" },
    { "id": 5, "name": "Ngân hàng thương mại cổ phần Bắc Á", "shortName": "Bac A Bank", "logo": "https://api.vietqr.io/img/BacABank.png" },
    { "id": 6, "name": "Ngân hàng thương mại cổ phần Đầu tư và Phát triển Việt Nam", "shortName": "BIDV", "logo": "https://api.vietqr.io/img/BIDV.png" },
    { "id": 8, "name": "Ngân hàng TNHH một thành viên Dầu Khí Toàn Cầu", "shortName": "GPBank", "logo": "https://api.vietqr.io/img/GPBank.png" },
    { "id": 9, "name": "Ngân hàng thương mại cổ phần Đông Á", "shortName": "DongA Bank", "logo": "https://api.vietqr.io/img/DongA Bank.png" },
    { "id": 10, "name": "Ngân hàng thương mại cổ phần Xuất Nhập khẩu Việt Nam", "shortName": "Eximbank", "logo": "https://api.vietqr.io/img/Eximbank.png" },
    { "id": 11, "name": "Ngân hàng thương mại cổ phần Phát triển Thành phố Hồ Chí Minh", "shortName": "HDBank", "logo": "https://api.vietqr.io/img/HDBank.png" },
    { "id": 13, "name": "Ngân hàng TNHH một thành viên Hong Leong Việt Nam", "shortName": "HongLeong", "logo": "https://api.vietqr.io/img/HongLeong.png" },
    { "id": 16, "name": "Ngân hàng thương mại cổ phần Kiên Long", "shortName": "KienLong Bank", "logo": "https://api.vietqr.io/img/KienLongBank.png" },
    { "id": 17, "name": "Ngân hàng TNHH một thành viên Đại chúng Việt Nam", "shortName": "Public Bank", "logo": "https://api.vietqr.io/img/PublicBank.png" },
    { "id": 18, "name": "Ngân hàng thương mại cổ phần Sài Gòn", "shortName": "SCB", "logo": "https://api.vietqr.io/img/SCB.png" },
    { "id": 19, "name": "Ngân hàng thương mại cổ phần Đông Nam Á", "shortName": "SeABank", "logo": "https://api.vietqr.io/img/SeABank.png" },
    { "id": 20, "name": "Ngân hàng thương mại cổ phần Sài Gòn - Hà Nội", "shortName": "SHB", "logo": "https://api.vietqr.io/img/SHB.png" },
    { "id": 21, "name": "Ngân hàng thương mại cổ phần Sài Gòn Thương Tín", "shortName": "Sacombank", "logo": "https://api.vietqr.io/img/Sacombank.png" },
    { "id": 22, "name": "Ngân hàng thương mại cổ phần Sài Gòn Công Thương", "shortName": "Saigonbank", "logo": "https://api.vietqr.io/img/SAIGONBANK.png" },
    { "id": 24, "name": "Ngân hàng thương mại cổ phần Kỹ Thương Việt Nam", "shortName": "Techcombank", "logo": "https://api.vietqr.io/img/TCB.png" },
    { "id": 25, "name": "Ngân hàng thương mại cổ phần Tiên Phong", "shortName": "TPBank", "logo": "https://api.vietqr.io/img/TPBank.png" },
    { "id": 26, "name": "Ngân hàng thương mại cổ phần Việt Á", "shortName": "VietABank", "logo": "https://api.vietqr.io/img/VietABank.png" },
    { "id": 27, "name": "Ngân hàng thương mại cổ phần Việt Nam Thịnh Vượng", "shortName": "VPBank", "logo": "https://api.vietqr.io/img/VPBank.png" },
    { "id": 28, "name": "Ngân hàng thương mại cổ phần Quốc Tế Việt Nam", "shortName": "VIB", "logo": "https://api.vietqr.io/img/VIB.png" },
    { "id": 29, "name": "Ngân hàng thương mại cổ phần Công Thương Việt Nam", "shortName": "VietinBank", "logo": "https://api.vietqr.io/img/VietinBank.png" },
    { "id": 30, "name": "Ngân hàng thương mại cổ phần Ngoại thương Việt Nam", "shortName": "Vietcombank", "logo": "https://api.vietqr.io/img/VCB.png" },
    { "id": 31, "name": "Ngân hàng thương mại cổ phần Hàng Hải Việt Nam", "shortName": "MSB", "logo": "https://api.vietqr.io/img/MSB.png" },
    { "id": 32, "name": "Ngân hàng thương mại cổ phần Nam Á", "shortName": "Nam A Bank", "logo": "https://api.vietqr.io/img/NamABank.png" },
    { "id": 33, "name": "Ngân hàng thương mại cổ phần Quốc Dân", "shortName": "NCB", "logo": "https://api.vietqr.io/img/NCB.png" },
    { "id": 34, "name": "Ngân hàng TNHH một thành viên Đại Dương", "shortName": "Oceanbank", "logo": "https://api.vietqr.io/img/Oceanbank.png" },
    { "id": 35, "name": "Ngân hàng thương mại cổ phần Xăng dầu Petrolimex", "shortName": "PGBank", "logo": "https://api.vietqr.io/img/PGBank.png" },
    { "id": 36, "name": "Ngân hàng thương mại cổ phần Việt Nam Thương Tín", "shortName": "VietBank", "logo": "https://api.vietqr.io/img/VIETBANK.png" },
    { "id": 37, "name": "Ngân hàng thương mại cổ phần Bưu điện Liên Việt", "shortName": "LienVietPostBank", "logo": "https://api.vietqr.io/img/LPB.png" },
    { "id": 38, "name": "Ngân hàng Quân đội", "shortName": "MBBank", "logo": "https://api.vietqr.io/img/MBBank.png" },
    { "id": 39, "name": "Ngân hàng thương mại cổ phần Bảo Việt", "shortName": "BaoViet Bank", "logo": "https://api.vietqr.io/img/BAOVIETBank.png" },
    { "id": 40, "name": "Ngân hàng TNHH một thành viên Shinhan Việt Nam", "shortName": "Shinhan Bank", "logo": "https://api.vietqr.io/img/SHBVN.png" },
    { "id": 41, "name": "Ngân hàng TNHH một thành viên CIMB Việt Nam", "shortName": "CIMB", "logo": "https://api.vietqr.io/img/CIMB.png" },
    { "id": 42, "name": "Ngân hàng KEB Hana – Chi nhánh Hà Nội", "shortName": "KEBHana", "logo": "https://api.vietqr.io/img/KEBHANAHCM.png" },
    { "id": 43, "name": "Ngân hàng Indovina", "shortName": "IVB", "logo": "https://api.vietqr.io/img/IVB.png" }
];
